const safeArray = (value) => (Array.isArray(value) ? value : []);

export const entityConfig = {
  clientes: {
    table: "clientes",
    toRow: (item) => ({
      id: item.id,
      nombre: item.nombre,
      nit: item.nit ?? null,
      telefono: item.telefono ?? null,
      ciudad: item.ciudad ?? null,
      direccion: item.direccion ?? null,
      contacto: item.contacto ?? null,
      email: item.email ?? null,
      estado: item.estado ?? null,
      notas: item.notas ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      nombre: row.nombre,
      nit: row.nit,
      telefono: row.telefono,
      ciudad: row.ciudad,
      direccion: row.direccion,
      contacto: row.contacto,
      email: row.email,
      estado: row.estado,
      notas: row.notas,
    }),
  },
  empleados: {
    table: "empleados",
    toRow: (item) => ({
      id: item.id,
      nombre: item.nombre,
      cargo: item.cargo ?? null,
      tel: item.tel ?? null,
      email: item.email ?? null,
      salario: item.salario ?? null,
      activo: item.activo ?? true,
      avatar: item.avatar ?? null,
      banco: item.banco ?? null,
      tipo_cuenta: item.tipoCuenta ?? null,
      numero_cuenta: item.numeroCuenta ?? null,
      extras: safeArray(item.horasExtrasPorObra),
      comisiones: safeArray(item.comisionesPorObra),
    }),
    fromRow: (row) => ({
      id: row.id,
      nombre: row.nombre,
      cargo: row.cargo,
      tel: row.tel,
      email: row.email,
      salario: row.salario,
      activo: row.activo,
      avatar: row.avatar,
      banco: row.banco,
      tipoCuenta: row.tipo_cuenta,
      numeroCuenta: row.numero_cuenta,
      horasExtrasPorObra: safeArray(row.extras),
      comisionesPorObra: safeArray(row.comisiones),
    }),
  },
  proveedores: {
    table: "proveedores",
    toRow: (item) => ({
      id: item.id,
      nombre: item.nombre,
      nit: item.nit ?? null,
      telefono: item.telefono ?? null,
      email: item.email ?? null,
      ciudad: item.ciudad ?? null,
      direccion: item.direccion ?? null,
      contacto: item.contacto ?? null,
      estado: item.estado ?? null,
      notas: item.notas ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      nombre: row.nombre,
      nit: row.nit,
      telefono: row.telefono,
      email: row.email,
      ciudad: row.ciudad,
      direccion: row.direccion,
      contacto: row.contacto,
      estado: row.estado,
      notas: row.notas,
    }),
  },
  obras: {
    table: "obras",
    toRow: (item) => ({
      id: item.id,
      cliente: item.cliente,
      nit: item.nit ?? null,
      tel: item.tel ?? null,
      proyecto: item.proyecto ?? null,
      ciudad: item.ciudad ?? null,
      direccion: item.direccion ?? null,
      coords: item.coords ?? null,
      estado: item.estado ?? null,
      avance: item.avance ?? null,
      total: item.total ?? null,
      pagado: item.pagado ?? null,
      saldo: item.saldo ?? null,
      costos: item.costos ?? null,
      fecha_inicio: item.fechaInicio ?? null,
      fecha_fin: item.fechaFin ?? null,
      empleados: safeArray(item.empleados),
      trazos: safeArray(item.trazos),
      anclajes: safeArray(item.anclajes),
      geo_mediciones: safeArray(item.geoMediciones),
      img_plano: item.imgPlano ?? null,
      img_sat: item.imgSat ?? null,
      geo_map_view: item.geoMapView ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      cliente: row.cliente,
      nit: row.nit,
      tel: row.tel,
      proyecto: row.proyecto,
      ciudad: row.ciudad,
      direccion: row.direccion,
      coords: row.coords,
      estado: row.estado,
      avance: row.avance,
      total: row.total,
      pagado: row.pagado,
      saldo: row.saldo,
      costos: row.costos,
      fechaInicio: row.fecha_inicio,
      fechaFin: row.fecha_fin,
      empleados: safeArray(row.empleados),
      trazos: safeArray(row.trazos),
      anclajes: safeArray(row.anclajes),
      geoMediciones: safeArray(row.geo_mediciones),
      imgPlano: row.img_plano,
      imgSat: row.img_sat,
      geoMapView: row.geo_map_view,
    }),
  },
  cotizaciones: {
    table: "cotizaciones",
    toRow: (item) => ({
      id: item.id,
      numero: item.numero ?? null,
      fecha: item.fecha ?? null,
      validez_dias: item.val ?? null,
      cliente: item.cliente ?? null,
      obra: item.obra ?? null,
      telefono: item.telefono ?? null,
      ciudad: item.ciudad ?? null,
      coords: item.coords ?? null,
      forma_pago: item.formaPago ?? null,
      tiempo_ejecucion: item.tiempoEjec ?? null,
      utilidad_pct: item.util ?? null,
      total: item.total ?? null,
      items: safeArray(item.items),
      map_img: item.mapImg ?? null,
      geo_mediciones: safeArray(item.geoMediciones),
      geo_map_view: item.geoMapView ?? null,
      estado: item.estado ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      numero: row.numero,
      fecha: row.fecha,
      val: row.validez_dias,
      cliente: row.cliente,
      obra: row.obra,
      telefono: row.telefono,
      ciudad: row.ciudad,
      coords: row.coords,
      formaPago: row.forma_pago,
      tiempoEjec: row.tiempo_ejecucion,
      util: row.utilidad_pct,
      total: row.total,
      items: safeArray(row.items),
      mapImg: row.map_img,
      geoMediciones: safeArray(row.geo_mediciones),
      geoMapView: row.geo_map_view,
      estado: row.estado,
    }),
  },
  certificaciones: {
    table: "certificaciones",
    toRow: (item) => ({
      id: item.id,
      obra_id: item.obraId ?? null,
      tipo: item.tipo ?? null,
      numero: item.numero ?? null,
      fecha: item.fecha ?? null,
      cliente: item.cliente ?? null,
      nit: item.nit ?? null,
      direccion: item.direccion ?? null,
      sistema: item.sistema ?? null,
      elementos: safeArray(item.elementos),
      normativa: item.normativa ?? null,
      ingeniero: item.ingeniero ?? null,
      matricula: item.matricula ?? null,
      estado: item.estado ?? null,
      prox_mant: item.proxMant ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      obraId: row.obra_id,
      tipo: row.tipo,
      numero: row.numero,
      fecha: row.fecha,
      cliente: row.cliente,
      nit: row.nit,
      direccion: row.direccion,
      sistema: row.sistema,
      elementos: safeArray(row.elementos),
      normativa: row.normativa,
      ingeniero: row.ingeniero,
      matricula: row.matricula,
      estado: row.estado,
      proxMant: row.prox_mant,
    }),
  },
  informes: {
    table: "informes",
    toRow: (item) => ({
      id: item.id,
      obra_id: item.obraId ?? null,
      proyecto: item.proyecto ?? null,
      localizacion: item.localizacion ?? null,
      fecha_informe: item.fechaInforme ?? null,
      periodo_inicio: item.periodoInicio ?? null,
      periodo_fin: item.periodoFin ?? null,
      personal: safeArray(item.personal),
      actividad: item.actividad ?? null,
      descripcion: item.descripcion ?? null,
      observaciones: item.observaciones ?? null,
      recomendaciones: item.recomendaciones ?? null,
      fotos: safeArray(item.fotos),
    }),
    fromRow: (row) => ({
      id: row.id,
      obraId: row.obra_id,
      proyecto: row.proyecto,
      localizacion: row.localizacion,
      fechaInforme: row.fecha_informe,
      periodoInicio: row.periodo_inicio,
      periodoFin: row.periodo_fin,
      personal: safeArray(row.personal),
      actividad: row.actividad,
      descripcion: row.descripcion,
      observaciones: row.observaciones,
      recomendaciones: row.recomendaciones,
      fotos: safeArray(row.fotos),
    }),
  },
  cuentas: {
    table: "cuentas_por_pagar",
    toRow: (item) => ({
      id: item.id,
      proveedor_id: item.proveedorId ?? null,
      obra_id: item.obraId ?? null,
      concepto: item.concepto ?? null,
      monto: item.monto ?? null,
      fecha: item.fecha ?? null,
      fecha_vence: item.fechaVence ?? null,
      estado: item.estado ?? null,
      factura: item.factura ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      proveedorId: row.proveedor_id,
      obraId: row.obra_id,
      concepto: row.concepto,
      monto: row.monto,
      fecha: row.fecha,
      fechaVence: row.fecha_vence,
      estado: row.estado,
      factura: row.factura,
    }),
  },
  pagos: {
    table: "pagos",
    toRow: (item) => ({
      id: item.id,
      obra_id: item.obraId ?? null,
      fecha: item.fecha ?? null,
      valor: item.valor ?? null,
      medio: item.medio ?? null,
      referencia: item.referencia ?? null,
      notas: item.notas ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      obraId: row.obra_id,
      fecha: row.fecha,
      valor: row.valor,
      medio: row.medio,
      referencia: row.referencia,
      notas: row.notas,
    }),
  },
  horarios: {
    table: "horarios",
    toRow: (item) => ({
      id: item.id,
      empleado_id: item.empleadoId ?? null,
      obra_id: item.obraId ?? null,
      fecha: item.fecha ?? null,
      hora_inicio: item.horaInicio ?? null,
      hora_fin: item.horaFin ?? null,
      horas: item.horas ?? null,
      notas: item.notas ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      empleadoId: row.empleado_id,
      obraId: row.obra_id,
      fecha: row.fecha,
      horaInicio: row.hora_inicio,
      horaFin: row.hora_fin,
      horas: row.horas,
      notas: row.notas,
    }),
  },
};

export const entityKeys = Object.keys(entityConfig);
