const safeArray = (value) => (Array.isArray(value) ? value : []);

export const entityConfig = {
  clientes: {
    table: "clientes",
    toRow: (item) => ({
      id: item.id,
      nombre: item.nombre,
      nit: item.nit ?? null,
      telefono: item.telefono ?? null,
      ciudad: item.ciudad ?? null,
      direccion: item.direccion ?? null,
      contacto: item.contacto ?? null,
      email: item.email ?? null,
      estado: item.estado ?? null,
      notas: item.notas ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      nombre: row.nombre,
      nit: row.nit,
      telefono: row.telefono,
      ciudad: row.ciudad,
      direccion: row.direccion,
      contacto: row.contacto,
      email: row.email,
      estado: row.estado,
      notas: row.notas,
    }),
  },
  empleados: {
    table: "empleados",
    toRow: (item) => ({
      id: item.id,
      nombre: item.nombre,
      cedula: item.cedula ?? null,
      cargo: item.cargo ?? null,
      tel: item.tel ?? null,
      email: item.email ?? null,
      salario: item.salario ?? null,
      activo: item.activo ?? true,
      avatar: item.avatar ?? null,
      tipo_contrato: item.tipoContrato ?? null,
      fecha_ingreso: item.fechaIngreso ?? null,
      fecha_salida: item.fechaSalida ?? null,
      causa_retiro: item.causaRetiro ?? null,
      vacaciones_pagadas_dias: item.vacacionesPagadasDias ?? 0,
      vacaciones_liquidacion_dias: item.vacacionesLiquidacionDias ?? null,
      banco: item.banco ?? null,
      tipo_cuenta: item.tipoCuenta ?? null,
      numero_cuenta: item.numeroCuenta ?? null,
      extras: safeArray(item.horasExtrasPorObra),
      comisiones: safeArray(item.comisionesPorObra),
      deducciones_personalizadas: safeArray(item.deduccionesPersonalizadas),
    }),
    toLegacyRow: (item) => ({
      id: item.id,
      nombre: item.nombre,
      cargo: item.cargo ?? null,
      tel: item.tel ?? null,
      email: item.email ?? null,
      salario: item.salario ?? null,
      activo: item.activo ?? true,
      avatar: item.avatar ?? null,
      banco: item.banco ?? null,
      tipo_cuenta: item.tipoCuenta ?? null,
      numero_cuenta: item.numeroCuenta ?? null,
      extras: safeArray(item.horasExtrasPorObra),
      comisiones: safeArray(item.comisionesPorObra),
    }),
    fromRow: (row) => ({
      id: row.id,
      nombre: row.nombre,
      cedula: row.cedula,
      cargo: row.cargo,
      tel: row.tel,
      email: row.email,
      salario: row.salario,
      activo: row.activo,
      avatar: row.avatar,
      tipoContrato: row.tipo_contrato,
      fechaIngreso: row.fecha_ingreso,
      fechaSalida: row.fecha_salida,
      causaRetiro: row.causa_retiro,
      vacacionesPagadasDias: Number(row.vacaciones_pagadas_dias ?? 0),
      vacacionesLiquidacionDias: row.vacaciones_liquidacion_dias === null || row.vacaciones_liquidacion_dias === undefined ? null : Number(row.vacaciones_liquidacion_dias),
      banco: row.banco,
      tipoCuenta: row.tipo_cuenta,
      numeroCuenta: row.numero_cuenta,
      horasExtrasPorObra: safeArray(row.extras),
      comisionesPorObra: safeArray(row.comisiones),
      deduccionesPersonalizadas: safeArray(row.deducciones_personalizadas),
    }),
  },
  cargos: {
    table: "cargos",
    optional: true,
    toRow: (item) => ({
      id: item.id,
      nombre: item.nombre,
      descripcion: item.descripcion ?? null,
      activo: item.activo ?? true,
    }),
    fromRow: (row) => ({
      id: row.id,
      nombre: row.nombre,
      descripcion: row.descripcion,
      activo: row.activo,
    }),
  },
  proveedores: {
    table: "proveedores",
    toRow: (item) => ({
      id: item.id,
      nombre: item.nombre,
      nit: item.nit ?? null,
      telefono: item.telefono ?? null,
      email: item.email ?? null,
      ciudad: item.ciudad ?? null,
      direccion: item.direccion ?? null,
      contacto: item.contacto ?? null,
      estado: item.estado ?? null,
      notas: item.notas ?? null,
      banco: item.banco ?? null,
      numero_cuenta: item.numeroCuenta ?? null,
      categoria: item.categoria ?? null,
      responsable_iva: item.responsableIva ?? item.responsable_iva ?? true,
      regimen_tributario: item.regimenTributario ?? item.regimen_tributario ?? null,
      agente_reteiva: item.agenteReteiva ?? item.agente_reteiva ?? false,
      autorretenedor_renta: item.autorretenedorRenta ?? item.autorretenedor_renta ?? false,
      municipio_ica: item.municipioIca ?? item.municipio_ica ?? null,
      codigo_ica: item.codigoIca ?? item.codigo_ica ?? null,
    }),
    toLegacyRow: (item) => ({
      id: item.id,
      nombre: item.nombre,
      nit: item.nit ?? null,
      telefono: item.telefono ?? null,
      email: item.email ?? null,
      ciudad: item.ciudad ?? null,
      direccion: item.direccion ?? null,
      contacto: item.contacto ?? null,
      estado: item.estado ?? null,
      notas: item.notas ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      nombre: row.nombre,
      nit: row.nit,
      telefono: row.telefono,
      email: row.email,
      ciudad: row.ciudad,
      direccion: row.direccion,
      contacto: row.contacto,
      estado: row.estado,
      notas: row.notas,
      banco: row.banco,
      numeroCuenta: row.numero_cuenta,
      categoria: row.categoria,
      responsableIva: row.responsable_iva,
      regimenTributario: row.regimen_tributario,
      agenteReteiva: row.agente_reteiva,
      autorretenedorRenta: row.autorretenedor_renta,
      municipioIca: row.municipio_ica,
      codigoIca: row.codigo_ica,
    }),
  },
  obras: {
    table: "obras",
    toRow: (item) => ({
      id: item.id,
      cliente: item.cliente,
      nit: item.nit ?? null,
      tel: item.tel ?? null,
      proyecto: item.proyecto ?? null,
      ciudad: item.ciudad ?? null,
      direccion: item.direccion ?? null,
      coords: item.coords ?? null,
      estado: item.estado ?? null,
      avance: item.avance ?? null,
      total: item.total ?? null,
      pagado: item.pagado ?? null,
      saldo: item.saldo ?? null,
      costos: item.costos ?? null,
      fecha_inicio: item.fechaInicio ?? null,
      fecha_fin: item.fechaFin ?? null,
      empleados: safeArray(item.empleados),
      trazos: safeArray(item.trazos),
      anclajes: safeArray(item.anclajes),
      geo_mediciones: safeArray(item.geoMediciones),
      img_plano: item.imgPlano ?? null,
      img_sat: item.imgSat ?? null,
      geo_map_view: item.geoMapView ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      cliente: row.cliente,
      nit: row.nit,
      tel: row.tel,
      proyecto: row.proyecto,
      ciudad: row.ciudad,
      direccion: row.direccion,
      coords: row.coords,
      estado: row.estado,
      avance: row.avance,
      total: row.total,
      pagado: row.pagado,
      saldo: row.saldo,
      costos: row.costos,
      fechaInicio: row.fecha_inicio,
      fechaFin: row.fecha_fin,
      empleados: safeArray(row.empleados),
      trazos: safeArray(row.trazos),
      anclajes: safeArray(row.anclajes),
      geoMediciones: safeArray(row.geo_mediciones),
      imgPlano: row.img_plano,
      imgSat: row.img_sat,
      geoMapView: row.geo_map_view,
    }),
  },
  cotizaciones: {
    table: "cotizaciones",
    toRow: (item) => ({
      id: item.id,
      numero: item.numero ?? null,
      fecha: item.fecha ?? null,
      validez_dias: item.val ?? null,
      cliente: item.cliente ?? null,
      obra: item.obra ?? null,
      telefono: item.telefono ?? null,
      ciudad: item.ciudad ?? null,
      coords: item.coords ?? null,
      texto_inicial: item.textoInicial ?? null,
      forma_pago: item.formaPago ?? null,
      tiempo_ejecucion: item.tiempoEjec ?? null,
      tipo_cotizacion: item.tipoCotizacion ?? null,
      requerimiento_cliente: item.requerimientoCliente ?? null,
      propuesta_nombre: item.propuestaNombre ?? null,
      propuesta_alcance: item.propuestaAlcance ?? null,
      propuesta_activa_id: item.propuestaActivaId ?? null,
      utilidad_pct: item.util ?? null,
      total: item.total ?? null,
      items: safeArray(item.items),
      propuestas: safeArray(item.propuestas),
      map_img: item.mapImg ?? null,
      geo_mediciones: safeArray(item.geoMediciones),
      fotos_cotizacion: safeArray(item.fotosCotizacion),
      geo_map_view: item.geoMapView ?? null,
      estado: item.estado ?? null,
    }),
    toLegacyRow: (item) => ({
      id: item.id,
      numero: item.numero ?? null,
      fecha: item.fecha ?? null,
      validez_dias: item.val ?? null,
      cliente: item.cliente ?? null,
      obra: item.obra ?? null,
      telefono: item.telefono ?? null,
      ciudad: item.ciudad ?? null,
      coords: item.coords ?? null,
      forma_pago: item.formaPago ?? null,
      tiempo_ejecucion: item.tiempoEjec ?? null,
      utilidad_pct: item.util ?? null,
      total: item.total ?? null,
      items: safeArray(item.items),
      map_img: item.mapImg ?? null,
      geo_mediciones: safeArray(item.geoMediciones),
      geo_map_view: item.geoMapView ?? null,
      estado: item.estado ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      numero: row.numero,
      fecha: row.fecha,
      val: row.validez_dias,
      cliente: row.cliente,
      obra: row.obra,
      telefono: row.telefono,
      ciudad: row.ciudad,
      coords: row.coords,
      textoInicial: row.texto_inicial,
      formaPago: row.forma_pago,
      tiempoEjec: row.tiempo_ejecucion,
      tipoCotizacion: row.tipo_cotizacion,
      requerimientoCliente: row.requerimiento_cliente,
      propuestaNombre: row.propuesta_nombre,
      propuestaAlcance: row.propuesta_alcance,
      propuestaActivaId: row.propuesta_activa_id,
      util: row.utilidad_pct,
      total: row.total,
      items: safeArray(row.items),
      propuestas: safeArray(row.propuestas),
      mapImg: row.map_img,
      geoMediciones: safeArray(row.geo_mediciones),
      fotosCotizacion: safeArray(row.fotos_cotizacion),
      geoMapView: row.geo_map_view,
      estado: row.estado,
    }),
  },
  certificaciones: {
    table: "certificaciones",
    toRow: (item) => ({
      id: item.id,
      obra_id: item.obraId ?? null,
      tipo: item.tipo ?? null,
      numero: item.numero ?? null,
      fecha: item.fecha ?? null,
      cliente: item.cliente ?? null,
      nit: item.nit ?? null,
      direccion: item.direccion ?? null,
      sistema: item.sistema ?? null,
      elementos: safeArray(item.elementos),
      normativa: item.normativa ?? null,
      ingeniero: item.ingeniero ?? null,
      matricula: item.matricula ?? null,
      estado: item.estado ?? null,
      prox_mant: item.proxMant ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      obraId: row.obra_id,
      tipo: row.tipo,
      numero: row.numero,
      fecha: row.fecha,
      cliente: row.cliente,
      nit: row.nit,
      direccion: row.direccion,
      sistema: row.sistema,
      elementos: safeArray(row.elementos),
      normativa: row.normativa,
      ingeniero: row.ingeniero,
      matricula: row.matricula,
      estado: row.estado,
      proxMant: row.prox_mant,
    }),
  },
  informes: {
    table: "informes",
    toRow: (item) => ({
      id: item.id,
      obra_id: item.obraId ?? null,
      proyecto: item.proyecto ?? null,
      localizacion: item.localizacion ?? null,
      fecha_informe: item.fechaInforme ?? null,
      periodo_inicio: item.periodoInicio ?? null,
      periodo_fin: item.periodoFin ?? null,
      personal: safeArray(item.personal),
      actividades: safeArray(item.actividades),
      actividad: item.actividad ?? null,
      descripcion: item.descripcion ?? null,
      observaciones: item.observaciones ?? null,
      recomendaciones: item.recomendaciones ?? null,
      fotos: safeArray(item.fotos),
    }),
    toLegacyRow: (item) => {
      const primeraActividad = safeArray(item.actividades)[0] ?? {};
      return {
        id: item.id,
        obra_id: item.obraId ?? null,
        proyecto: item.proyecto ?? null,
        localizacion: item.localizacion ?? null,
        fecha_informe: item.fechaInforme ?? null,
        periodo_inicio: item.periodoInicio ?? null,
        periodo_fin: item.periodoFin ?? null,
        personal: safeArray(item.personal),
        actividad: item.actividad ?? primeraActividad.titulo ?? null,
        descripcion: item.descripcion ?? primeraActividad.descripcion ?? null,
        observaciones: item.observaciones ?? primeraActividad.observaciones ?? null,
        recomendaciones: item.recomendaciones ?? null,
        fotos: safeArray(item.fotos).length ? safeArray(item.fotos) : safeArray(primeraActividad.fotos),
      };
    },
    fromRow: (row) => {
      const legacyFotos = safeArray(row.fotos);
      const actividades = safeArray(row.actividades);
      const actividadesNormalizadas = actividades.length
        ? actividades
        : (
            row.actividad || row.descripcion || row.observaciones || legacyFotos.length
              ? [{
                  titulo: row.actividad ?? "",
                  descripcion: row.descripcion ?? "",
                  observaciones: row.observaciones ?? "",
                  fotos: legacyFotos,
                }]
              : []
          );
      return {
      id: row.id,
      obraId: row.obra_id,
      proyecto: row.proyecto,
      localizacion: row.localizacion,
      fechaInforme: row.fecha_informe,
      periodoInicio: row.periodo_inicio,
      periodoFin: row.periodo_fin,
      personal: safeArray(row.personal),
      actividad: row.actividad,
      descripcion: row.descripcion,
      observaciones: row.observaciones,
      recomendaciones: row.recomendaciones,
      fotos: legacyFotos,
      actividades: actividadesNormalizadas,
      };
    },
  },
  cuentas: {
    table: "cuentas_por_pagar",
    toRow: (item) => ({
      id: item.id,
      proveedor_id: item.proveedorId ?? null,
      obra_id: item.obraId ?? null,
      concepto: item.concepto ?? null,
      monto: item.monto ?? null,
      fecha: item.fecha ?? null,
      fecha_vence: item.fechaVence ?? null,
      estado: item.estado ?? null,
      factura: item.factura ?? null,
      tipo_operacion: item.tipoOperacion ?? item.tipo_operacion ?? null,
      subtotal: item.subtotal ?? null,
      tarifa_iva: item.tarifaIva ?? item.tarifa_iva ?? null,
      valor_iva: item.valorIva ?? item.valor_iva ?? null,
      concepto_ret_fuente: item.conceptoRetFuente ?? item.concepto_ret_fuente ?? null,
      base_ret_fuente: item.baseRetFuente ?? item.base_ret_fuente ?? null,
      tarifa_ret_fuente: item.tarifaRetFuente ?? item.tarifa_ret_fuente ?? null,
      valor_ret_fuente: item.valorRetFuente ?? item.valor_ret_fuente ?? null,
      aplica_reteiva: item.aplicaReteiva ?? item.aplica_reteiva ?? false,
      base_reteiva: item.baseReteiva ?? item.base_reteiva ?? null,
      tarifa_reteiva: item.tarifaReteiva ?? item.tarifa_reteiva ?? null,
      valor_reteiva: item.valorReteiva ?? item.valor_reteiva ?? null,
      municipio_reteica: item.municipioReteica ?? item.municipio_reteica ?? null,
      actividad_ica: item.actividadIca ?? item.actividad_ica ?? null,
      codigo_ica: item.codigoIca ?? item.codigo_ica ?? null,
      base_reteica: item.baseReteica ?? item.base_reteica ?? null,
      tarifa_reteica: item.tarifaReteica ?? item.tarifa_reteica ?? null,
      valor_reteica: item.valorReteica ?? item.valor_reteica ?? null,
      valor_bruto_factura: item.valorBrutoFactura ?? item.valor_bruto_factura ?? null,
      valor_total_retenciones: item.valorTotalRetenciones ?? item.valor_total_retenciones ?? null,
      valor_total_pagar: item.valorTotalPagar ?? item.valor_total_pagar ?? null,
      observacion_tributaria: item.observacionTributaria ?? item.observacion_tributaria ?? null,
      saldo_pendiente_actual: item.saldoPendienteActual ?? item.saldo_pendiente_actual ?? null,
      monto_pagado: item.montoPagado ?? item.monto_pagado ?? null,
      pagos_historial: safeArray(item.pagosHistorial ?? item.pagos_historial),
      fecha_pago: item.fechaPago ?? item.fecha_pago ?? null,
    }),
    toLegacyRow: (item) => ({
      id: item.id,
      proveedor_id: item.proveedorId ?? null,
      obra_id: item.obraId ?? null,
      concepto: item.concepto ?? null,
      monto: item.monto ?? null,
      fecha: item.fecha ?? null,
      fecha_vence: item.fechaVence ?? null,
      estado: item.estado ?? null,
      factura: item.factura ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      proveedorId: row.proveedor_id,
      obraId: row.obra_id,
      concepto: row.concepto,
      monto: row.monto,
      fecha: row.fecha,
      fechaVence: row.fecha_vence,
      estado: row.estado,
      factura: row.factura,
      tipoOperacion: row.tipo_operacion,
      subtotal: row.subtotal,
      tarifaIva: row.tarifa_iva,
      valorIva: row.valor_iva,
      conceptoRetFuente: row.concepto_ret_fuente,
      baseRetFuente: row.base_ret_fuente,
      tarifaRetFuente: row.tarifa_ret_fuente,
      valorRetFuente: row.valor_ret_fuente,
      aplicaReteiva: row.aplica_reteiva,
      baseReteiva: row.base_reteiva,
      tarifaReteiva: row.tarifa_reteiva,
      valorReteiva: row.valor_reteiva,
      municipioReteica: row.municipio_reteica,
      actividadIca: row.actividad_ica,
      codigoIca: row.codigo_ica,
      baseReteica: row.base_reteica,
      tarifaReteica: row.tarifa_reteica,
      valorReteica: row.valor_reteica,
      valorBrutoFactura: row.valor_bruto_factura,
      valorTotalRetenciones: row.valor_total_retenciones,
      valorTotalPagar: row.valor_total_pagar,
      observacionTributaria: row.observacion_tributaria,
      saldoPendienteActual: row.saldo_pendiente_actual,
      montoPagado: row.monto_pagado,
      pagosHistorial: safeArray(row.pagos_historial),
      fechaPago: row.fecha_pago,
    }),
  },
  pagos: {
    table: "pagos",
    toRow: (item) => ({
      id: item.id,
      obra_id: item.obraId ?? null,
      fecha: item.fecha ?? null,
      valor: item.monto ?? item.valor ?? null,
      medio: item.metodo ?? item.medio ?? null,
      referencia: item.referencia ?? item.tipo ?? null,
      tipo: item.tipo ?? null,
      estado: item.estado ?? null,
      notas: item.notas ?? null,
    }),
    toLegacyRow: (item) => ({
      id: item.id,
      obra_id: item.obraId ?? null,
      fecha: item.fecha ?? null,
      valor: item.monto ?? item.valor ?? null,
      medio: item.metodo ?? item.medio ?? null,
      referencia: item.referencia ?? item.tipo ?? null,
      notas: item.notas ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      obraId: row.obra_id,
      fecha: row.fecha,
      monto: Number(row.valor ?? 0),
      valor: Number(row.valor ?? 0),
      metodo: row.medio,
      medio: row.medio,
      tipo: row.tipo ?? row.referencia ?? "Abono",
      estado: row.estado ?? "Pagado",
      referencia: row.referencia,
      notas: row.notas,
    }),
  },
  horarios: {
    table: "horarios",
    toRow: (item) => ({
      id: item.id,
      empleado_id: item.empleadoId ?? null,
      obra_id: item.obraId ?? null,
      fecha: item.fecha ?? null,
      hora_inicio: item.horaInicio ?? null,
      hora_fin: item.horaFin ?? null,
      horas: item.horas ?? null,
      notas: item.notas ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      empleadoId: row.empleado_id,
      obraId: row.obra_id,
      fecha: row.fecha,
      horaInicio: row.hora_inicio,
      horaFin: row.hora_fin,
      horas: row.horas,
      notas: row.notas,
    }),
  },
  contabilidad_config: {
    table: "contabilidad_config",
    optional: true,
    toRow: (item) => ({
      id: item.id,
      razon_social: item.razonSocial ?? null,
      nit: item.nit ?? null,
      marco_normativo: item.marcoNormativo ?? null,
      marco_normativo_label: item.marcoNormativoLabel ?? null,
      moneda: item.moneda ?? null,
      uvt: item.uvt ?? null,
      auto_cxc: item.autoCxc ?? true,
      auto_cxp: item.autoCxp ?? true,
      auto_nomina: item.autoNomina ?? true,
      cuenta_banco: item.cuentaBanco ?? null,
      cuenta_caja: item.cuentaCaja ?? null,
      cuenta_clientes: item.cuentaClientes ?? null,
      cuenta_proveedores: item.cuentaProveedores ?? null,
      cuenta_iva_descontable: item.cuentaIvaDescontable ?? null,
      cuenta_iva_generado: item.cuentaIvaGenerado ?? null,
      cuenta_retefuente: item.cuentaRetefuente ?? null,
      cuenta_reteiva: item.cuentaReteiva ?? null,
      cuenta_reteica: item.cuentaReteica ?? null,
      cuenta_ingreso_servicios: item.cuentaIngresoServicios ?? null,
      cuenta_costo_materiales: item.cuentaCostoMateriales ?? null,
      cuenta_costo_servicios_obra: item.cuentaCostoServiciosObra ?? null,
      cuenta_gasto_servicios: item.cuentaGastoServicios ?? null,
      cuenta_gasto_honorarios: item.cuentaGastoHonorarios ?? null,
      cuenta_gasto_arrendamiento: item.cuentaGastoArrendamiento ?? null,
      cuenta_gasto_diverso: item.cuentaGastoDiverso ?? null,
      cuenta_nomina_sueldos: item.cuentaNominaSueldos ?? null,
      cuenta_nomina_extras: item.cuentaNominaExtras ?? null,
      cuenta_nomina_auxilio: item.cuentaNominaAuxilio ?? null,
      cuenta_nomina_liquidaciones: item.cuentaNominaLiquidaciones ?? null,
      cuenta_nomina_por_pagar: item.cuentaNominaPorPagar ?? null,
      cuenta_salud_por_pagar: item.cuentaSaludPorPagar ?? null,
      cuenta_pension_por_pagar: item.cuentaPensionPorPagar ?? null,
      cuenta_otras_deducciones_nomina: item.cuentaOtrasDeduccionesNomina ?? null,
      observaciones: item.observaciones ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      razonSocial: row.razon_social,
      nit: row.nit,
      marcoNormativo: row.marco_normativo,
      marcoNormativoLabel: row.marco_normativo_label,
      moneda: row.moneda,
      uvt: row.uvt,
      autoCxc: row.auto_cxc,
      autoCxp: row.auto_cxp,
      autoNomina: row.auto_nomina,
      cuentaBanco: row.cuenta_banco,
      cuentaCaja: row.cuenta_caja,
      cuentaClientes: row.cuenta_clientes,
      cuentaProveedores: row.cuenta_proveedores,
      cuentaIvaDescontable: row.cuenta_iva_descontable,
      cuentaIvaGenerado: row.cuenta_iva_generado,
      cuentaRetefuente: row.cuenta_retefuente,
      cuentaReteiva: row.cuenta_reteiva,
      cuentaReteica: row.cuenta_reteica,
      cuentaIngresoServicios: row.cuenta_ingreso_servicios,
      cuentaCostoMateriales: row.cuenta_costo_materiales,
      cuentaCostoServiciosObra: row.cuenta_costo_servicios_obra,
      cuentaGastoServicios: row.cuenta_gasto_servicios,
      cuentaGastoHonorarios: row.cuenta_gasto_honorarios,
      cuentaGastoArrendamiento: row.cuenta_gasto_arrendamiento,
      cuentaGastoDiverso: row.cuenta_gasto_diverso,
      cuentaNominaSueldos: row.cuenta_nomina_sueldos,
      cuentaNominaExtras: row.cuenta_nomina_extras,
      cuentaNominaAuxilio: row.cuenta_nomina_auxilio,
      cuentaNominaLiquidaciones: row.cuenta_nomina_liquidaciones,
      cuentaNominaPorPagar: row.cuenta_nomina_por_pagar,
      cuentaSaludPorPagar: row.cuenta_salud_por_pagar,
      cuentaPensionPorPagar: row.cuenta_pension_por_pagar,
      cuentaOtrasDeduccionesNomina: row.cuenta_otras_deducciones_nomina,
      observaciones: row.observaciones,
    }),
  },
  plan_cuentas: {
    table: "plan_cuentas",
    optional: true,
    toRow: (item) => ({
      id: item.id ?? item.codigo,
      codigo: item.codigo ?? item.id,
      nombre: item.nombre ?? null,
      naturaleza: item.naturaleza ?? null,
      grupo_reporte: item.grupoReporte ?? item.grupo_reporte ?? null,
      categoria_estado: item.categoriaEstado ?? item.categoria_estado ?? null,
      permite_movimientos: item.permiteMovimientos ?? item.permite_movimientos ?? true,
      requiere_tercero: item.requiereTercero ?? item.requiere_tercero ?? false,
      requiere_centro_costo: item.requiereCentroCosto ?? item.requiere_centro_costo ?? false,
      cuenta_padre: item.cuentaPadre ?? item.cuenta_padre ?? null,
      activo: item.activo ?? true,
      descripcion: item.descripcion ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      codigo: row.codigo,
      nombre: row.nombre,
      naturaleza: row.naturaleza,
      grupoReporte: row.grupo_reporte,
      categoriaEstado: row.categoria_estado,
      permiteMovimientos: row.permite_movimientos,
      requiereTercero: row.requiere_tercero,
      requiereCentroCosto: row.requiere_centro_costo,
      cuentaPadre: row.cuenta_padre,
      activo: row.activo,
      descripcion: row.descripcion,
    }),
  },
  asientos_contables: {
    table: "asientos_contables",
    optional: true,
    toRow: (item) => ({
      id: item.id,
      consecutivo: item.consecutivo ?? null,
      fecha: item.fecha ?? null,
      periodo: item.periodo ?? null,
      tipo_comprobante: item.tipoComprobante ?? item.tipo_comprobante ?? null,
      estado: item.estado ?? null,
      automatico: item.automatico ?? false,
      origen: item.origen ?? null,
      origen_ref: item.origenRef ?? item.origen_ref ?? null,
      descripcion: item.descripcion ?? null,
      tercero_id: item.terceroId ?? item.tercero_id ?? null,
      tercero_nombre: item.terceroNombre ?? item.tercero_nombre ?? null,
      soporte: item.soporte ?? null,
      lineas: safeArray(item.lineas),
      total_debito: item.totalDebito ?? item.total_debito ?? null,
      total_credito: item.totalCredito ?? item.total_credito ?? null,
      diferencia: item.diferencia ?? null,
    }),
    fromRow: (row) => ({
      id: row.id,
      consecutivo: row.consecutivo,
      fecha: row.fecha,
      periodo: row.periodo,
      tipoComprobante: row.tipo_comprobante,
      estado: row.estado,
      automatico: row.automatico,
      origen: row.origen,
      origenRef: row.origen_ref,
      descripcion: row.descripcion,
      terceroId: row.tercero_id,
      terceroNombre: row.tercero_nombre,
      soporte: row.soporte,
      lineas: safeArray(row.lineas),
      totalDebito: row.total_debito,
      totalCredito: row.total_credito,
      diferencia: row.diferencia,
    }),
  },
  nominas_generadas: {
    table: "nominas_generadas",
    toRow: (item) => ({
      id: item.id,
      mes: item.periodoMes ?? item.snapshot?.periodo?.mes ?? null,
      corte: item.periodoCorte ?? item.snapshot?.periodo?.corte ?? null,
      label: item.periodoLabel ?? item.snapshot?.periodo?.label ?? null,
      fecha_inicio: item.snapshot?.periodo?.startIso ?? null,
      fecha_fin: item.snapshot?.periodo?.endIso ?? null,
      dias_referencia: item.snapshot?.periodo?.diasReferencia ?? null,
      generado_en: item.generadoEn ?? new Date().toISOString(),
      totals: item.snapshot?.totals ?? {},
      registros: safeArray(item.snapshot?.registros),
      registros_banco: safeArray(item.snapshot?.registrosBanco),
      plano_banco: item.planoBanco ?? null,
      archivo_banco: item.planoBanco ? `NOMINA_${item.periodoMes ?? item.snapshot?.periodo?.mes ?? "CORTE"}_${String(item.periodoCorte ?? item.snapshot?.periodo?.corte ?? "").toUpperCase()}.txt` : null,
    }),
    fromRow: (row) => ({
      id: row.id,
      periodoMes: row.mes,
      periodoCorte: row.corte,
      periodoLabel: row.label,
      generadoEn: row.generado_en,
      snapshot: {
        id: row.id,
        generadoEn: row.generado_en,
        periodo: {
          mes: row.mes,
          corte: row.corte,
          label: row.label,
          startIso: row.fecha_inicio,
          endIso: row.fecha_fin,
          diasReferencia: row.dias_referencia,
        },
        registros: row.registros ?? [],
        registrosBanco: row.registros_banco ?? [],
        totals: row.totals ?? {},
      },
      planoBanco: row.plano_banco ?? "",
    }),
  },
};

export const entityKeys = Object.keys(entityConfig);
